USE DATABASE de_project1;
USE SCHEMA raw;

COPY INTO customers
FROM @~/customers.csv
FILE_FORMAT = (TYPE = CSV, FIELD_OPTIONALLY_ENCLOSED_BY = '"', SKIP_HEADER = 1);

COPY INTO products
FROM @~/products.csv
FILE_FORMAT = (TYPE = CSV, FIELD_OPTIONALLY_ENCLOSED_BY = '"', SKIP_HEADER = 1);

COPY INTO orders
FROM @~/orders.csv
FILE_FORMAT = (TYPE = CSV, FIELD_OPTIONALLY_ENCLOSED_BY = '"', SKIP_HEADER = 1);